----------------------------------------------------------------
-- Create All Tables
----------------------------------------------------------------

-- Table: user_roles
CREATE TABLE public.user_roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role varchar NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);

-- Table: users
CREATE TABLE public.users (
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_role_id integer NOT NULL,
    email varchar NOT NULL,
    password_hash varchar NOT NULL,
    full_name varchar NULL,
    photo_url varchar NULL,
    created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
    auth_user_id uuid NULL,
    is_approved bool NOT NULL DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_user_role_id_fkey FOREIGN KEY (user_role_id) 
        REFERENCES public.user_roles (id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- Table: project_status
CREATE TABLE public.project_status (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status varchar NOT NULL,
    CONSTRAINT project_status_pkey PRIMARY KEY (id)
);

-- Table: model_categories
CREATE TABLE public.model_categories (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_category varchar NOT NULL,
    CONSTRAINT model_categories_pkey PRIMARY KEY (id)
);

-- Table: model_status
CREATE TABLE public.model_status (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status varchar NOT NULL,
    CONSTRAINT model_status_pkey PRIMARY KEY (id)
);

-- Table: portfolio_pages
CREATE TABLE public.portfolio_pages (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    portfolio_page_name varchar NOT NULL,
    creator_id integer NOT NULL,
    auth_user_id uuid NULL,
    CONSTRAINT portfolio_pages_pkey PRIMARY KEY (id),
    CONSTRAINT portfolio_pages_creator_id_fkey FOREIGN KEY (creator_id) 
        REFERENCES public.users (user_id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: projects
CREATE TABLE public.projects (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_name varchar NOT NULL,
    event_start_date date NULL,
    project_status_id integer NOT NULL,
    creator_id integer NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_creator_id_fkey FOREIGN KEY (creator_id) 
        REFERENCES public.users (user_id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT projects_project_status_id_fkey FOREIGN KEY (project_status_id) 
        REFERENCES public.project_status (id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- Table: project_clients
CREATE TABLE public.project_clients (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT project_clients_pkey PRIMARY KEY (id),
    CONSTRAINT project_clients_project_id_fkey FOREIGN KEY (project_id) 
        REFERENCES public.projects (id) 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT project_clients_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users (user_id) 
        ON DELETE CASCADE ON UPDATE NO ACTION
);

-- Table: models
CREATE TABLE public.models (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_name varchar NOT NULL,
    project_id integer NOT NULL,
    model_category_id integer NULL,
    created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
    status_id integer NULL,
    CONSTRAINT models_pkey PRIMARY KEY (id),
    CONSTRAINT models_model_category_id_fkey FOREIGN KEY (model_category_id) 
        REFERENCES public.model_categories (id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT models_project_id_fkey FOREIGN KEY (project_id) 
        REFERENCES public.projects (id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT models_status_id_fkey FOREIGN KEY (status_id) 
        REFERENCES public.model_status (id) 
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Table: model_versions
CREATE TABLE public.model_versions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_id integer NOT NULL,
    version integer NOT NULL,
    obj_file_path varchar NOT NULL,
    can_download bool NOT NULL DEFAULT false,
    created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
    thumbnail_url text NOT NULL DEFAULT ''::text,
    CONSTRAINT model_versions_pkey PRIMARY KEY (id),
    CONSTRAINT model_versions_model_id_fkey FOREIGN KEY (model_id) 
        REFERENCES public.models (id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: model_images
CREATE TABLE public.model_images (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_version_id integer NOT NULL,
    image_path varchar NOT NULL,
    CONSTRAINT model_images_pkey PRIMARY KEY (id),
    CONSTRAINT model_images_model_version_id_fkey FOREIGN KEY (model_version_id) 
        REFERENCES public.model_versions (id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: comments
CREATE TABLE public.comments (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_version_id integer NOT NULL,
    comment_text text NOT NULL,
    created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
    user_id integer NOT NULL,
    auth_user_id uuid NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_model_version_id_fkey FOREIGN KEY (model_version_id) 
        REFERENCES public.model_versions (id) 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users (user_id) 
        ON DELETE CASCADE ON UPDATE NO ACTION
);

-- Table: user_favourites
CREATE TABLE public.user_favourites (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_version_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT user_favourites_pkey PRIMARY KEY (id),
    CONSTRAINT user_favourites_model_version_id_fkey FOREIGN KEY (model_version_id) 
        REFERENCES public.model_versions (id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT user_favourites_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users (user_id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: portfolio_page_models
CREATE TABLE public.portfolio_page_models (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    portfolio_page_id integer NOT NULL,
    model_id integer NOT NULL,
    CONSTRAINT portfolio_page_models_pkey PRIMARY KEY (id),
    CONSTRAINT portfolio_page_models_model_id_fkey FOREIGN KEY (model_id) 
        REFERENCES public.models (id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT portfolio_page_models_portfolio_page_id_fkey FOREIGN KEY (portfolio_page_id) 
        REFERENCES public.portfolio_pages (id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

----------------------------------------------------------------
-- Populate Lookup Tables
----------------------------------------------------------------

-- 1. Populate user_roles
INSERT INTO public.user_roles (id, role) VALUES
    (1, 'CREATOR'),
    (2, 'USER'),
    (3, 'ADMIN')
ON CONFLICT (id) DO NOTHING;

-- Fix the auto-increment counter for user_roles
SELECT setval(pg_get_serial_sequence('public.user_roles', 'id'), (SELECT MAX(id) FROM public.user_roles));


-- 2. Populate project_status
INSERT INTO public.project_status (id, status) VALUES
    (1, 'In Progress'),
    (2, 'Complete')
ON CONFLICT (id) DO NOTHING;

-- Fix the auto-increment counter for project_status
SELECT setval(pg_get_serial_sequence('public.project_status', 'id'), (SELECT MAX(id) FROM public.project_status));


-- 3. Populate model_status
INSERT INTO public.model_status (id, status) VALUES
    (1, 'Awaiting Client Review'),
    (2, 'Client Feedback Received'),
    (3, 'In Revision'),
    (4, 'Approved'),
    (5, 'Discontinued')
ON CONFLICT (id) DO NOTHING;

-- Fix the auto-increment counter for model_status
SELECT setval(pg_get_serial_sequence('public.model_status', 'id'), (SELECT MAX(id) FROM public.model_status));


-- 4. Populate model_categories
INSERT INTO public.model_categories (id, model_category) VALUES
    (1, 'Reception'),
    (2, 'Wedding Ceremony'),
    (3, 'Mehendi'),
    (4, 'Sangeet'),
    (5, 'Haldi Ceremony'),
    (6, 'Birthday Party')
ON CONFLICT (id) DO NOTHING;

-- Fix the auto-increment counter for model_categories
SELECT setval(pg_get_serial_sequence('public.model_categories', 'id'), (SELECT MAX(id) FROM public.model_categories));


----------------------------------------------------------------
-- Create the Buckets (Model Images and 3D Model Files
----------------------------------------------------------------

-- Create 'Models' bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('Models', 'Models', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Create 'Model Images' bucket (Note: ID contains a space)
INSERT INTO storage.buckets (id, name, public)
VALUES ('Model Images', 'Model Images', true)
ON CONFLICT (id) DO UPDATE SET public = true;